name: quantdesk
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.27.0
  - pandas=2.2.2
  - scipy=1.13.0
  - scikit-learn=1.5.0
  - matplotlib=3.9.1
  - seaborn=0.13.2
  - plotly=5.22.0
  - jupyter
  - jupyterlab=4.2.3
  - ipywidgets=8.1.3
  - notebook
  - redis-py=5.0.7
  - psycopg2=2.9.9
  - sqlalchemy=2.0.31
  - click=8.1.7
  - pydantic=2.8.1
  - fastapi=0.111.0
  - uvicorn=0.30.0
  - aiohttp=3.9.5
  - websockets=12.0
  - python-dotenv=1.0.1
  - pyarrow=16.1.0
  - git
  - curl
  - pip:
    - ta==0.10.2
    - backtrader==1.9.78.123
    - vectorbt==0.26.0
    - mlflow==2.14.1
    - torch==2.3.0
    - yfinance==0.2.40
    - alpaca-trade-api==3.0.0
    - ccxt==4.3.37
    - structlog==24.1.0
    - scikit-optimize==0.9.0
    - arch==6.3.0
    - quantstats==0.0.62
    - alembic==1.13.2
    - apscheduler==3.10.4
    - prometheus-client==0.20.0
    - discord-webhook==1.3.1
    - fastavro==1.9.4
    - statsmodels==0.15.0
    - ruff==0.4.5
    - black==24.3.0
    - mypy==1.10.0
    - pytest==8.2.0
    - pytest-cov==5.0.0
    - pytest-xdist==3.6.0
    - pytest-asyncio==0.23.7
    - bandit==1.7.9
    - pre-commit==3.7.1
    - mkdocs-material==9.5.18
    - mkdocstrings[python]==0.25.0
    - jupyter-book==1.0.0
    - pdoc==14.5.1
    - httpx==0.27.0
    - pytest-mock==3.14.0
    - factory-boy==3.3.0
    - freezegun==1.5.1 